services:
  - type: static
    name: vite-emilia
    runtime: node
    buildCommand: pnpm install && pnpm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
