services:
  - type: static
    name: vite-emilia
    env: static
    buildCommand: pnpm run build
    publishPath: ./dist/client
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
