name: autofix.ci # needed to securely identify the workflow

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: write

env:
  PNPM_ONLY_BUILT_DEPENDENCIES: sharp

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run lint/format scripts
        uses: area44/workflows/lint-format@v4.4.0
