name: lint-format

on:
  pull_request:
  push:
    branches: ["main"]
permissions:
  contents: read

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Format with oxfmt
        run: pnpm run format

      - name: Run autofix.ci
        uses: autofix-ci/action@v1.3
